---
- name: put the minecraft service
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: 0755
  notify:
  - restart minecraft
- name: enable the minecraft service
  service:
    name: minecraft
    state: started
    enabled: yes
