---
- name: update and clean all packages of apt
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
  when: ansible_facts['os_family'] == 'Debian'
- name: update and clean all packages of yum
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
  ignore_errors: yes
